### ISSUE TITLE
NumeralFieldFormatter move cursor wrong.

### ISSUE THREAD

**Issue by jable8** [johannesh2/textfieldformatter#12]
Hi, thanks for the addon it looks very nice. I'm using the `NumeralFieldFormatter`. 

`new NumeralFieldFormatter(".", ",", 2).extend(txtMoneda);`

If you type a number and then move the cursor to a previous position and start typing  new numbers, `NumeralFieldFormatter` sometimes moves the cursor to the left of the new number typed, you can see this behavior also in Custom numeral formatting  of the [demo online](http://johku.app.fi/textfieldformatter/).

You can reproduce this issue typing a number, for example 12345678,9,  move the cursor between 7 and 8, then start typing 12345...  you will see most of the time the cursor moves to the right when a new number is typed (as it should be) but sometimes it moves to the left.

I've checked the Numeral formatting on the  [Cleave.js demo]( https://nosir.github.io/cleave.js/) and this issue never happens.

Do you know any way to avoid this issue?

Thanks in advance,
Regards.

**Comment by johannesh2** [comment]
Thanks for the report. I could first check if updating Cleave.js helps.

**Comment by johannesh2** [comment]
With a quick test updating Cleave.js from 1.1 to 1.4 seems to help. I'll release an updated add-on.

**Comment by jable8** [comment]
Ok, that sounds good!. Do you know more or less when are you going to update that? Because we've a release to a costumer coming soon and if this issue is not updated we would have to find another solution.
Thanks you very much!

**Comment by johannesh2** [comment]
Version 2.1 available in Maven.

**Comment by johannesh2** [comment]
Demo updated to 2.1 also

**Comment by johannesh2** [comment]
Please re-open if issue persists.

**Comment by jable8** [comment]
The issue seems to me solved, thanks you very much! 
Regards
