### ISSUE TITLE
4.0.0.beta2 seems to reference Johannes local dev environment

### ISSUE THREAD

**Issue by epricer** [johannesh2/textfieldformatter#19]
the released jar includes references to "C:\Users\Johannes\github\textfieldformatter\target\checkout", which causes this to show up in the logs in projects using the component:
```2019-08-26 16:10:45.348  INFO 72422 --- [  restartedMain] c.v.f.server.startup.DevModeInitializer  : Starting dev-mode updaters in C:\Users\Johannes\github\textfieldformatter\target\checkout folder.```
This subsequently results in the fatal exception:
```java.lang.IllegalArgumentException: 'other' is different type of Path```

Notably:

- I'm on a Mac, and my name is not Johnanes.
- This problem does not occur with 4.0.0.beta1.
- The bundled dependency (jar) includes flow-build-info.json file with that folder referenced.

**Comment by johannesh2** [comment]
I’ll take a look at it. Thanks for reporting

**Comment by johannesh2** [comment]
Should be fixed now in beta3
