### ISSUE TITLE
Enable the ability to strip leading zeros on the NumeralFieldFormatter

### ISSUE THREAD

**Issue by RobertoAffonso** [johannesh2/textfieldformatter#23]
Hello! Im using the NumeralFieldFormatter to display the current value in Brazilian Reais, however im currently trying to format the value in order to display the leading zeros. For example if the user types in '10' it should format to 0,10 representing 10 cents. Cleave.js has a boolean value in the NumeralFieldFormatter called stripLeadingZeroes which by default it is set to true, it would be great to have this option on the TextFieldFormatter addon.

**Comment by johannesh2** [comment]
Fixed in 4.1
