### ISSUE TITLE
Copy and Paste Doesn't Preserve Formatting

### ISSUE THREAD

**Issue by yavkozlyuk** [johannesh2/textfieldformatter#27]
As a way to resolve https://github.com/nosir/cleave.js/issues/454 issue for textfieldformatter i suggest adding copyDelimiter property to CleaveConfiguration.class

**Comment by johannesh2** [comment]
Thanks for the tip. It looks like a good option. What do you think, would I be brave enough to make it the new default?

**Comment by yavkozlyuk** [comment]
I'm pretty sure that would be a great decision

**Comment by johannesh2** [comment]
Fixed_ in 5.0.0.
