### ISSUE TITLE
will make the Numeral formatting?

### ISSUE THREAD

**Issue by fabioebner** [johannesh2/textfieldformatter#4]

**Comment by johannesh2** [comment]
Yeah I could take a look at it and try. Unfortunately not this weekend as I'm away from computer. I'll get back to you.

**Comment by fabioebner** [comment]
Tks man, I will wait ( I need a money format, when type he put the brazilian mask) 123.123.323,33

tks

**Comment by fabioebner** [comment]
Hei man, Did you see that problem for me? tks

**Comment by johannesh2** [comment]
Sorry I have been too busy with both work and personal things. I'll try again tomorrow.

**Comment by johannesh2** [comment]
I'm very sorry this took me so long. v.1.3 available.

**Comment by fabioebner** [comment]
Tks man. 

It`s possible to use one text field to have more than one format, depends on my user choice`s? Sample: I have one text field  and 2 radiobutton, when my user select the first radio my format will be ###.###.###-## and if my user click in second radio the format will be ##.###.###/####-##. and my user can change between  one or other any time

tks

**Comment by johannesh2** [comment]
Currrently no. I would need to implement a setFormat method to the formatter. I'm not sure if cleave.js even supports having format ##.###.###/####-## where the # is limited for numbers only. I would have to check. Could you comment on #5 if you need more specifics.
