### ISSUE TITLE
Possibility to change the format of a text field without recreating the field

### ISSUE THREAD

**Issue by johannesh2** [johannesh2/textfieldformatter#5]
I have one text field and 2 radiobutton, when my user select the first radio my format will be ###.###.###-## and if my user click in second radio the format will be ##.###.###/####-##. and my user can change between one or other any time

**Comment by fabioebner** [comment]
I appreciate your quick answer, but my problem was not the format, I already does this with delimiters, my problem is when I need to use the same textfield and change the mask that will use 

tks

**Comment by johannesh2** [comment]
Fixed in 1.5
